services:
  - type: web
    name: interview-prep-flashcards
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist/flashcard-app/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
